# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FabAssesment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'MBProgressHUD'
pod 'ReachabilitySwift', '~> 4.0'

  # Pods for FabAssesment

  target 'FabAssesmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FabAssesmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
